"""Standalone live River research dashboard; no execution controls."""
PAGE = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live Bitcoin token learning</title><style>
body{background:#0d1827;color:#e9f2fc;font:16px system-ui;max-width:1150px;margin:auto;padding:24px}a{color:#7fe4d3}p{line-height:1.6;color:#b9cbdf}.panel{background:#1a2b40;padding:20px;border-radius:14px;margin:16px 0}.cards{display:flex;flex-wrap:wrap;gap:14px}.card{flex:1;min-width:150px}.big{font-size:27px;font-weight:bold}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:9px;text-align:right;border-bottom:1px solid #3e526a}td:first-child,th:first-child{text-align:left}.scroll{overflow:auto}.badge{color:#ffc77e}canvas{width:100%;height:230px}code{color:#8fe6d7}</style>
<h1>Live Bitcoin token learning · River</h1><p><a href="ecology.html">Market ecology</a> · <a href="tokens.html">Historical token laboratory</a> · <a href="river_checkpoint.json" download="river_checkpoint.json">Download learning checkpoint</a></p>
<p>Active Bitcoin venue → 12 small tokens per book update → a lightweight online model → a 30-second price-change forecast. It scores each forecast when the later outcome arrives, then learns. Absolute prices are used to calculate outcomes, never as input tokens.</p>
<div class="panel"><div id="status" class="big">Connecting…</div><p id="session"></p><p class="badge">Trading status: WAIT · research only · no qualified buy/sell signal</p><p id="persistence"></p></div>
<div class="panel cards" id="counts"></div>
<div class="panel"><h2>Is the forecast improving?</h2><div class="cards" id="metrics"></div><p>Positive skill means lower squared forecast error than predicting no price change. It does not mean profitable trading. The prior-mean baseline uses only outcomes known at the decision. These are adaptive forward scores, not an untouched holdout; overlapping outcomes are correlated.</p><p id="forecast"></p><canvas id="chart"></canvas><p>Recent matured forecasts and actual 30-second midpoint changes, in basis points (1 bp = 0.01%). Teal: forecast. Gold: observed outcome.</p></div>
<div class="panel"><h2>What is happening in the tape?</h2><div class="scroll"><table><thead><tr><th>Field</th><th>Observed value</th><th>Token bucket (0–7)</th></tr></thead><tbody id="tokens"></tbody></table></div><p>Each venue has its own model and checkpoint. Fixed bins were declared before this live run. Tokens describe aggregated updates and anonymous flow. Adds/removals are displayed liquidity changes near the midpoint; removals are not proven cancellations. No participant identity is inferred.</p></div>
<div class="panel"><h2>Flow and later price response</h2><div class="scroll"><table><thead><tr><th>State at decision</th><th>Outcomes</th><th>Mean later return, bp</th></tr></thead><tbody id="patterns"></tbody></table></div><p>Descriptive associations, not causes or confirmed strategies. Compare repeated responses across independent periods before using them. Tied or balanced liquidity changes use the bid-withdrawal category by convention.</p></div>
<div class="panel"><h2>How to read this laboratory</h2><p>First watch “learned outcomes” increase. Then inspect skill and compare the two baseline errors. In the response table, look for a state whose later price reaction repeats in new periods. A trading candidate still needs a frozen model, separate evaluation periods, and realistic fees, slippage and latency. A billion tokens alone cannot establish an edge.</p><p>First outcomes can arrive after about 30 seconds of uninterrupted valid observations. Early hours are a system check; multiple days and market conditions are needed to investigate repeatability. No fixed amount of training guarantees profitability.</p></div>
<script>
const el=id=>document.getElementById(id),num=(v,n=4)=>v==null?'—':Number(v).toFixed(n);function card(label,value){let d=document.createElement('div');d.className='card';let t=document.createElement('div');t.textContent=label;let b=document.createElement('div');b.className='big';b.textContent=value;d.append(t,b);return d}function rows(id,items){el(id).replaceChildren(...items.map(values=>{let r=document.createElement('tr');for(let v of values){let c=document.createElement('td');c.textContent=v;r.append(c)}return r}))}function clear(reason){el('status').textContent=reason;for(let id of ['counts','metrics','tokens','patterns'])el(id).replaceChildren();el('forecast').textContent='No current forecast';let c=el('chart');c.getContext('2d').clearRect(0,0,c.width,c.height)}
function chart(recent){let c=el('chart');c.width=c.clientWidth;c.height=230;let ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!recent.length)return;let values=recent.flatMap(r=>[r.forecast_bps,r.actual_bps]),lo=Math.min(0,...values),hi=Math.max(0,...values);if(hi===lo){hi=1;lo=-1}ctx.fillStyle='#b9cbdf';ctx.fillText(num(lo,2)+' to '+num(hi,2)+' bp',12,16);for(let [field,color] of [['forecast_bps','#7fe4d3'],['actual_bps','#ffc77e']]){ctx.strokeStyle=color;ctx.beginPath();recent.forEach((r,i)=>{let x=16+i/Math.max(1,recent.length-1)*(c.width-32),y=28+(hi-r[field])/(hi-lo)*184;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke()}}
async function draw(){try{let started=performance.now(),r=await fetch('river_live.json',{cache:'no-store',signal:AbortSignal.timeout(2500)});if(!r.ok)throw Error('unavailable');let s=await r.json(),now=Number(r.headers.get('X-Observer-Time-Ms')),age=now-s.generated_ns/1e6;if(!now||age<0||age+performance.now()-started>2500){clear('Observer offline or delayed · learning status unavailable');return}el('status').textContent=s.status;el('session').textContent=s.venue+' · '+s.version+' · session '+s.session+(s.restored?' · restored checkpoint':' · new model session');el('persistence').textContent=s.persistence;el('counts').replaceChildren(...[['Book updates',s.events],['Tokens',s.tokens],['Forecasts',s.decisions],['Learned outcomes',s.learned_outcomes],['Pending',s.pending],['Discarded labels',s.discarded_labels]].map(([k,v])=>card(k,Number(v).toLocaleString())));el('metrics').replaceChildren(...[['Model MSE (bp²)',num(s.mse_bps2)],['No-change MSE',num(s.zero_baseline_mse_bps2)],['Prior-mean MSE',num(s.prior_mean_baseline_mse_bps2)],['Skill vs no change',s.skill_vs_zero==null?'—':num(s.skill_vs_zero*100,2)+'%']].map(([k,v])=>card(k,v)));el('forecast').textContent=s.forecast?'Latest research forecast: '+num(s.forecast.forecast_bps)+' bp over 30 seconds · outcome pending.':'No pending forecast';rows('tokens',s.latest?Object.entries(s.latest.values).map(([k,v])=>[k,num(v),s.latest.tokens[k]]):[]);rows('patterns',Object.entries(s.patterns).map(([k,v])=>[k,v.count,num(v.sum_bps/v.count)]));chart(s.recent)}catch(e){clear('Cannot load live learning status')}}draw();setInterval(draw,1000);
</script></html>'''
